### ISSUE TITLE
kuntarajat-ok.json kuntaliitosten jälkeen?

### ISSUE THREAD

**Issue by sdahlbac** [tomimick/mapcolorizer#1]
Kunnat liittyvät, esim: 
https://fi.wikipedia.org/wiki/Kuntaliitos_Suomessa#2015

Miten tuota kuntarajat-ok.json saa ajan tasalle? Vai onko helpointa vaan vaihtaa esim. Jalasjärven koodi 164 -> Kurikan koodiksi 301 ?

**Comment by sdahlbac** [comment]
I investigated this a bit myself, and while I could not produce exactly the same thing the following worked for me:

First off, started using this guide to get a clipped borders 
https://github.com/kansanmuisti/datavaalit/wiki/kuntarajat-leikkatuna-suomen-rantaviivalla (with slight modifications due to qgis 2.16 having slightly different menus etc)

Then, 
run

`python conv.py geojson` on that

after the following applying the following

```diff
-        name = m["properties"]["name"]
+        name = m["properties"]["text"]
+        name = name.split(":")[1].split(",")[0]     # text is in this format:  "(2:Savukoski,Savukoski)"
+        m["properties"]["name"] = name
```

The `python conv.py cut` I could not get to work due to differences in geometry types or somesuch, so I used `https://mapshaper.org` instead

Now, I could not get qgis to produce a geojson in EPSG:4326, (probably due to me being a n00b), so I used ogr2ogr instead: 

`ogr2ogr dest.geojson  src-3067.geojson -t_srs EPSG:4326`

And voilà, an updated kuntarajat geojson file.
Hope this helps someone (including myself, when I have to do it the next time :)

**Comment by tomimick** [comment]
Thanks for the code+data update @sdahlbac ! Sorry I have not noticed this feedback. 

Wish i had time to update the data file, 4y is a long time...
